# CalenDO iCal Importer Configuration
database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: calendo
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Logging configuration (optional)
logging:
  level: info
  file: "logs/importer.log"
