{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calendo.backend.fullname" . }}-config
  labels:
    {{- include "calendo.backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- toYaml .Values.backend.configMapData | nindent 2 }}
{{- end }}
