{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calendoapi.fullname" . }}-backend-config
  labels:
    {{- include "calendoapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- toYaml .Values.backend.configMapData | nindent 2 }}
{{- end }}
