{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calendo.backend.fullname" . }}
  labels:
    {{- include "calendo.backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calendo.backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calendo.backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calendo.backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      {{- if .Values.cnpg.enabled }}
      initContainers:
      - name: config-injector
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          cp /original-config/config.yaml /shared-config/config.yaml
          sed -i "s/password: \"\"/password: \"$DB_PASSWORD\"/" /shared-config/config.yaml
          echo "Config file updated with database password"
          cat /shared-config/config.yaml
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cnpg.database.secret }}
              key: password
        volumeMounts:
        - name: original-config-volume
          mountPath: /original-config
        - name: shared-config-volume
          mountPath: /shared-config
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.backend.env.ENVIRONMENT | quote }}
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "calendo.backend.fullname" . }}-db-credentials
                  key: DB_USER
            {{- if .Values.cnpg.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cnpg.database.secret }}
                  key: password
            {{- else }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "calendo.backend.fullname" . }}-db-credentials
                  key: DB_PASSWORD
            {{- end }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "calendo.backend.fullname" . }}-db-credentials
                  key: DB_NAME
          volumeMounts:
            {{- if .Values.cnpg.enabled }}
            - name: shared-config-volume
              mountPath: /app/configs
            {{- else }}
            - name: config-volume
              mountPath: /app/configs
            {{- end }}
          {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.httpGet.path }}
              port: {{ .Values.backend.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.httpGet.path }}
              port: {{ .Values.backend.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        {{- if .Values.cnpg.enabled }}
        - name: original-config-volume
          configMap:
            name: {{ include "calendo.backend.fullname" . }}-config
        - name: shared-config-volume
          emptyDir: {}
        {{- else }}
        - name: config-volume
          configMap:
            name: {{ include "calendo.backend.fullname" . }}-config
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
