{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpg.cluster.name }}
  labels:
    {{- include "calendo.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.cnpg.cluster.instances }}
  
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database.name }}
      owner: {{ .Values.cnpg.database.owner }}
  
  storage:
    size: {{ .Values.cnpg.storage.size }}
    {{- if .Values.cnpg.storage.storageClass }}
    storageClass: {{ .Values.cnpg.storage.storageClass }}
    {{- end }}

  # Ensure proper resource limits and requests
  resources:
    requests:
      memory: {{ .Values.cnpg.resources.requests.memory | quote }}
      cpu: {{ .Values.cnpg.resources.requests.cpu | quote }}
    limits:
      memory: {{ .Values.cnpg.resources.limits.memory | quote }}
      cpu: {{ .Values.cnpg.resources.limits.cpu | quote }}
{{- end }}
