{{- if .Values.icalImporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calendo.icalimporter.fullname" . }}
  labels:
    {{- include "calendo.icalimporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: ical-importer
data:
{{- with .Values.icalImporter.configMapData }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
