{{- if and .Values.icalImporter.enabled .Values.icalImporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "calendo.icalimporter.serviceAccountName" . }}
  labels:
    {{- include "calendo.icalimporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: ical-importer
  {{- with .Values.icalImporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
