{{- if .Values.imageGenerator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendo.imagegenerator.fullname" . }}
  labels:
    {{- include "calendo.imagegenerator.labels" . | nindent 4 }}
    app.kubernetes.io/component: imagegenerator
spec:
  type: {{ .Values.imageGenerator.service.type }}
  ports:
    - port: {{ .Values.imageGenerator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calendo.imagegenerator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: imagegenerator
{{- end }}
