{{- if and .Values.imageGenerator.enabled .Values.imageGenerator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "calendo.imagegenerator.serviceAccountName" . }}
  labels:
    {{- include "calendo.imagegenerator.labels" . | nindent 4 }}
    app.kubernetes.io/component: imagegenerator
  {{- with .Values.imageGenerator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
