{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendoapi.fullname" . }}-backend
  labels:
    {{- include "calendoapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calendoapi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
