# CalenDO API Configuration
port: 8080
environment: development

# Database configuration
database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: calendo
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Logging configuration
logging:
  level: debug
  file: "logs/api.log"

# CORS settings
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
